# Generated by Django 2.2.3 on 2019-07-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190706_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.CharField(max_length=20, null=True, verbose_name='Tag'),
        ),
    ]
