# Generated by Django 2.2.3 on 2019-07-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190706_0850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='News',
        ),
    ]
